### ISSUE TITLE
error when viewing /projects when not loggged in

### ISSUE THREAD

**Issue by kjorg50** [scalableinternetservicesarchive/LaPlaya#10]
![no_login_projects_error](https://cloud.githubusercontent.com/assets/3325973/4989913/c18b4ea4-6934-11e4-95d7-43f678295fd0.png)

When you are not logged in you should be able to view projects, right? I get this page. 

Viewing `/galleries` and `/comments` work when not logged in

**Comment by jhenkens** [comment]
Should just be
`if can? :edit, project`

where project is the local variable from the block.

**Comment by jhenkens** [comment]
When defining 'abilities' of a user in the `ability.rb` file, we use the `can :edit, Project, user_id: user.id` (note, not `uid`, `uid` is only used for omniauth, we want just the standard id column). This uses the defining syntax of `can`, not the checking syntax of `can?`. In `can?`, we only need to pass two arguments typically, the action, and the actual object we are working on (Or just the class, if we are checking for index/new/create actions, since those don't have a specific object instance).

Aka,

`can? :update, @project`
`can? :create, Project`

**Comment by jasenmh** [comment]
I think this one is fixed with the same fix from #9 . If you check for an attribute on current_user, but there is no current_user, bad rails things happen.

**Comment by jasenmh** [comment]
Fixed.
